CREATE OR REPLACE FUNCTION obter_descricao_produt 
    (p_COD PRODUTO_EXERCICIO.COD%type) 
RETURN PRODUTO_EXERCICIO.DESCRICAO%type 

IS 
    v_DESCRICAO PRODUTO_EXERCICIO.DESCRICAO%type;
BEGIN
    SELECT DESCRICAO INTO v_DESCRICAO FROM PRODUTO_EXERCICIO WHERE COD = p_COD;
    RETURN v_DESCRICAO;
END;

SELECT obter_descricao_produt(COD) FROM PRODUTO_EXERCICIO WHERE COD = 1;