CREATE OR REPLACE FUNCTION categoria_cliente
    (p_FATURAMENTO IN CLIENTE.FATURAMENTO_PREVISTO%type)
RETURN CLIENTE.CATEGORIA%type
IS
    v_CATEGORIA CLIENTE.CATEGORIA%type;
BEGIN 
    IF p_FATURAMENTO <= 10000 THEN
        v_CATEGORIA := 'PEQUENO PORTE';
    ELSIF p_FATURAMENTO <= 50000 THEN
        v_CATEGORIA := 'MEDIO PORTE';
    ELSIF p_FATURAMENTO >= 100000 THEN
        v_CATEGORIA := 'MÉDIO GRANDE PORTE';
    ELSE
        v_CATEGORIA := 'GRANDE PORTE';
    END IF;
    RETURN v_CATEGORIA;
END;