CREATE OR REPLACE PROCEDURE incluir_cliente
(
p_ID CLIENTE.ID%type,
p_RAZAO CLIENTE.RAZAO_SOCIAL%type,
p_CNPJ CLIENTE.CNPJ%type,
p_SEGMERCADO CLIENTE.SEGMERCADO_ID%type,
p_FATURAMENTO CLIENTE.FATURAMENTO_PREVISTO%type,
p_CATEGORIA CLIENTE.CATEGORIA%type
)
IS 
BEGIN
    INSERT INTO CLIENTE 
    VALUES (p_ID, p_RAZAO, p_CNPJ, p_SEGMERCADO, SYSDATE,p_FATURAMENTO, p_CATEGORIA);
    COMMIT;
END;

EXECUTE incluir_cliente(1, 'SUPERMERCADO CHAMPIONS', '70.707.070/0001-70', 1, 20000, 'PEQUENO');

SELECT * FROM CLIENTE