CREATE OR REPLACE PROCEDURE INSENT_PRODUCT (
   v_COD    IN VARCHAR2,
   v_DESCRICAO   IN VARCHAR2,
   v_CATEGORIA          IN VARCHAR2
)
IS
BEGIN
   INSERT INTO PRODUTO_EXERCICIO (COD, DESCRICAO, CATEGORIA)
   VALUES (v_COD, v_DESCRICAO, v_CATEGORIA);
   
   COMMIT;
END;