SET SERVEROUTPUT ON
 
 DECLARE
    v_FATURAMENTO CLIENTE.FATURAMENTO_PREVISTO%type := 5000;
    v_CATEGORIA CLIENTE.CATEGORIA%type;
 BEGIN
    IF v_FATURAMENTO <= 10000 THEN
        v_CATEGORIA := 'PEQUENO PORTE';
    ELSIF v_FATURAMENTO <= 50000 THEN
        v_CATEGORIA := 'MEDIO PORTE';
    ELSIF v_FATURAMENTO >= 100000 THEN
        v_CATEGORIA := 'MÉDIO GRANDE PORTE';
    ELSE
        v_CATEGORIA := 'GRANDE PORTE';
    END IF;
    dbms_output.put_line(v_CATEGORIA);
 END;
 
 
 SELECT * FROM CLIENTE