CREATE OR REPLACE PROCEDURE incluir_cliente
    (
    p_ID CLIENTE.ID%type,
    p_RAZAO CLIENTE.RAZAO_SOCIAL%type,
    p_CNPJ CLIENTE.CNPJ%type,
    p_SEGMERCADO CLIENTE.SEGMERCADO_ID%type,
    p_FATURAMENTO CLIENTE.FATURAMENTO_PREVISTO%type,
    )
IS 
    v_CATEGORIA CLIENTE.CATEGORIA%type
BEGIN
    v_CATEGORIA := categoria_cliente(p_FATURAMENTO);
    INSERT INTO CLIENTE 
    VALUES (p_ID, p_RAZAO, p_CNPJ, p_SEGMERCADO, SYSDATE,p_FATURAMENTO, v_CATEGORIA);
    COMMIT;
END;